### ISSUE TITLE
Add absolute time column to the processed data

### ISSUE THREAD

**Issue by brosaplanella** [paramm-team/data_processing#11]
The parser should also include an absolute time data and, if not available in the raw data, craft it from the experiment duration and starting time.

**Comment by PipGrylls** [comment]
In the segmenter we have reset time, is this similar?

**Comment by brosaplanella** [comment]
Not quite. The reset time method resets the relative time in the segmented data (so it starts at zero again). This PR is to add (when possible) an extra column with the absolute time of the experiment (i.e. the datetime when measurements were taken) which is sometimes needed to sync multiple datasets. @AlexandruPascu is almost done with that, so I assigned him this issue.

**Comment by AlexandruPascu** [comment]
Yep, Ferran is right. The reset time method is to reset the time after a segmentation has been done so it's easier to plot and follow. I've just added the functionality for the extra column with the absolute time taken when available from either the data itself or the metadata.
